# Generated by Django 4.1.13 on 2024-07-02 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryFromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['send_time'],
            },
        ),
        migrations.AddIndex(
            model_name='queryfromuser',
            index=models.Index(fields=['send_time'], name='run_string__send_ti_a7b09d_idx'),
        ),
    ]
